// Generated by scripts/generate-companion-contracts.mjs. Do not edit by hand.
import Foundation

let companionMinimumProtocolVersion = 1
let companionProtocolVersion = 1

func companionProtocolVersionIsSupported(_ version: Int) -> Bool {
    version >= companionMinimumProtocolVersion && version <= companionProtocolVersion
}

enum CompanionEventType: Hashable, Codable {
    case snapshotCreated
    case projectCreated
    case projectUpdated
    case goalCreated
    case goalUpdated
    case decisionCreated
    case decisionUpdated
    case agentRunCreated
    case agentRunUpdated
    case agentRunArchived
    case agentMessageCreated
    case artifactUpdated
    case morningBriefingUpdated
    case workAssistantMessageCreated
    case workAssistantMessageUpdated
    case agentTurnSettled
    case modelLabelsUpdated
    case commandUpdated
    case unknown(String)

    var rawValue: String {
        switch self {
        case .snapshotCreated: "snapshot.created"
        case .projectCreated: "project.created"
        case .projectUpdated: "project.updated"
        case .goalCreated: "goal.created"
        case .goalUpdated: "goal.updated"
        case .decisionCreated: "decision.created"
        case .decisionUpdated: "decision.updated"
        case .agentRunCreated: "agent-run.created"
        case .agentRunUpdated: "agent-run.updated"
        case .agentRunArchived: "agent-run.archived"
        case .agentMessageCreated: "agent-message.created"
        case .artifactUpdated: "artifact.updated"
        case .morningBriefingUpdated: "morning-briefing.updated"
        case .workAssistantMessageCreated: "work-assistant-message.created"
        case .workAssistantMessageUpdated: "work-assistant-message.updated"
        case .agentTurnSettled: "agent-turn.settled"
        case .modelLabelsUpdated: "model-labels.updated"
        case .commandUpdated: "command.updated"
        case .unknown(let value): value
        }
    }

    init(from decoder: Decoder) throws {
        let value = try decoder.singleValueContainer().decode(String.self)
        switch value {
        case "snapshot.created": self = .snapshotCreated
        case "project.created": self = .projectCreated
        case "project.updated": self = .projectUpdated
        case "goal.created": self = .goalCreated
        case "goal.updated": self = .goalUpdated
        case "decision.created": self = .decisionCreated
        case "decision.updated": self = .decisionUpdated
        case "agent-run.created": self = .agentRunCreated
        case "agent-run.updated": self = .agentRunUpdated
        case "agent-run.archived": self = .agentRunArchived
        case "agent-message.created": self = .agentMessageCreated
        case "artifact.updated": self = .artifactUpdated
        case "morning-briefing.updated": self = .morningBriefingUpdated
        case "work-assistant-message.created": self = .workAssistantMessageCreated
        case "work-assistant-message.updated": self = .workAssistantMessageUpdated
        case "agent-turn.settled": self = .agentTurnSettled
        case "model-labels.updated": self = .modelLabelsUpdated
        case "command.updated": self = .commandUpdated
        default: self = .unknown(value)
        }
    }

    func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(rawValue)
    }
}

enum CompanionCommandType: Hashable, Codable {
    case assistantSendMessage
    case assistantExecuteAction
    case agentSendMessage
    case agentStopMessage
    case agentRenameSession
    case agentUpdateDraftPrompt
    case agentArchiveSession
    case artifactRequestUpload
    case decisionUpdateStatus
    case decisionHandle
    case projectUpdate
    case unknown(String)

    var rawValue: String {
        switch self {
        case .assistantSendMessage: "assistant.send-message"
        case .assistantExecuteAction: "assistant.execute-action"
        case .agentSendMessage: "agent.send-message"
        case .agentStopMessage: "agent.stop-message"
        case .agentRenameSession: "agent.rename-session"
        case .agentUpdateDraftPrompt: "agent.update-draft-prompt"
        case .agentArchiveSession: "agent.archive-session"
        case .artifactRequestUpload: "artifact.request-upload"
        case .decisionUpdateStatus: "decision.update-status"
        case .decisionHandle: "decision.handle"
        case .projectUpdate: "project.update"
        case .unknown(let value): value
        }
    }

    init(from decoder: Decoder) throws {
        let value = try decoder.singleValueContainer().decode(String.self)
        switch value {
        case "assistant.send-message": self = .assistantSendMessage
        case "assistant.execute-action": self = .assistantExecuteAction
        case "agent.send-message": self = .agentSendMessage
        case "agent.stop-message": self = .agentStopMessage
        case "agent.rename-session": self = .agentRenameSession
        case "agent.update-draft-prompt": self = .agentUpdateDraftPrompt
        case "agent.archive-session": self = .agentArchiveSession
        case "artifact.request-upload": self = .artifactRequestUpload
        case "decision.update-status": self = .decisionUpdateStatus
        case "decision.handle": self = .decisionHandle
        case "project.update": self = .projectUpdate
        default: self = .unknown(value)
        }
    }

    func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(rawValue)
    }
}
