// Generated by scripts/generate-companion-contracts.mjs. Do not edit by hand.
import Foundation

let companionMinimumProtocolVersion = 4
let companionProtocolVersion = 4
let companionContractFingerprint = "6a26404c459ace85b596ffd0"

func companionProtocolVersionIsSupported(_ version: Int) -> Bool {
    version >= companionMinimumProtocolVersion && version <= companionProtocolVersion
}

func companionProtocolRangeSupportsLocalVersion(minimumVersion: Int, currentVersion: Int) -> Bool {
    companionProtocolVersion >= minimumVersion && companionProtocolVersion <= currentVersion
}

func companionContractFingerprintIsSupported(_ fingerprint: String?) -> Bool {
    fingerprint == nil || fingerprint == companionContractFingerprint
}

enum CompanionEventType: Hashable, Codable {
    case snapshotCreated
    case chatPageUpdated
    case projectCreated
    case projectUpdated
    case goalCreated
    case goalUpdated
    case decisionCreated
    case decisionUpdated
    case agentRunCreated
    case agentRunUpdated
    case agentRunArchived
    case agentMessageCreated
    case artifactUpdated
    case morningBriefingUpdated
    case workAssistantMessageCreated
    case workAssistantMessageUpdated
    case agentTurnSettled
    case modelLabelsUpdated
    case commandUpdated
    case unknown(String)

    var rawValue: String {
        switch self {
        case .snapshotCreated: "snapshot.created"
        case .chatPageUpdated: "chat-page.updated"
        case .projectCreated: "project.created"
        case .projectUpdated: "project.updated"
        case .goalCreated: "goal.created"
        case .goalUpdated: "goal.updated"
        case .decisionCreated: "decision.created"
        case .decisionUpdated: "decision.updated"
        case .agentRunCreated: "agent-run.created"
        case .agentRunUpdated: "agent-run.updated"
        case .agentRunArchived: "agent-run.archived"
        case .agentMessageCreated: "agent-message.created"
        case .artifactUpdated: "artifact.updated"
        case .morningBriefingUpdated: "morning-briefing.updated"
        case .workAssistantMessageCreated: "work-assistant-message.created"
        case .workAssistantMessageUpdated: "work-assistant-message.updated"
        case .agentTurnSettled: "agent-turn.settled"
        case .modelLabelsUpdated: "model-labels.updated"
        case .commandUpdated: "command.updated"
        case .unknown(let value): value
        }
    }

    init(from decoder: Decoder) throws {
        let value = try decoder.singleValueContainer().decode(String.self)
        switch value {
        case "snapshot.created": self = .snapshotCreated
        case "chat-page.updated": self = .chatPageUpdated
        case "project.created": self = .projectCreated
        case "project.updated": self = .projectUpdated
        case "goal.created": self = .goalCreated
        case "goal.updated": self = .goalUpdated
        case "decision.created": self = .decisionCreated
        case "decision.updated": self = .decisionUpdated
        case "agent-run.created": self = .agentRunCreated
        case "agent-run.updated": self = .agentRunUpdated
        case "agent-run.archived": self = .agentRunArchived
        case "agent-message.created": self = .agentMessageCreated
        case "artifact.updated": self = .artifactUpdated
        case "morning-briefing.updated": self = .morningBriefingUpdated
        case "work-assistant-message.created": self = .workAssistantMessageCreated
        case "work-assistant-message.updated": self = .workAssistantMessageUpdated
        case "agent-turn.settled": self = .agentTurnSettled
        case "model-labels.updated": self = .modelLabelsUpdated
        case "command.updated": self = .commandUpdated
        default: self = .unknown(value)
        }
    }

    func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(rawValue)
    }
}

enum CompanionCommandType: Hashable, Codable {
    case assistantSendMessage
    case assistantExecuteAction
    case agentSendMessage
    case agentStopMessage
    case agentCreateSession
    case agentRenameSession
    case agentUpdateDraftPrompt
    case agentArchiveSession
    case chatLoadHistory
    case artifactRequestUpload
    case decisionUpdateStatus
    case decisionHandle
    case projectUpdate
    case unknown(String)

    var rawValue: String {
        switch self {
        case .assistantSendMessage: "assistant.send-message"
        case .assistantExecuteAction: "assistant.execute-action"
        case .agentSendMessage: "agent.send-message"
        case .agentStopMessage: "agent.stop-message"
        case .agentCreateSession: "agent.create-session"
        case .agentRenameSession: "agent.rename-session"
        case .agentUpdateDraftPrompt: "agent.update-draft-prompt"
        case .agentArchiveSession: "agent.archive-session"
        case .chatLoadHistory: "chat.load-history"
        case .artifactRequestUpload: "artifact.request-upload"
        case .decisionUpdateStatus: "decision.update-status"
        case .decisionHandle: "decision.handle"
        case .projectUpdate: "project.update"
        case .unknown(let value): value
        }
    }

    init(from decoder: Decoder) throws {
        let value = try decoder.singleValueContainer().decode(String.self)
        switch value {
        case "assistant.send-message": self = .assistantSendMessage
        case "assistant.execute-action": self = .assistantExecuteAction
        case "agent.send-message": self = .agentSendMessage
        case "agent.stop-message": self = .agentStopMessage
        case "agent.create-session": self = .agentCreateSession
        case "agent.rename-session": self = .agentRenameSession
        case "agent.update-draft-prompt": self = .agentUpdateDraftPrompt
        case "agent.archive-session": self = .agentArchiveSession
        case "chat.load-history": self = .chatLoadHistory
        case "artifact.request-upload": self = .artifactRequestUpload
        case "decision.update-status": self = .decisionUpdateStatus
        case "decision.handle": self = .decisionHandle
        case "project.update": self = .projectUpdate
        default: self = .unknown(value)
        }
    }

    func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(rawValue)
    }
}

struct AssistantSendMessagePayload: Codable {
    let prompt: String
    let attachments: [AttachmentDescriptor]?
}

struct AssistantExecuteActionPayload: Codable {
    let messageId: String
    let proposalId: String
    let optionId: String
}

struct AgentSendMessagePayload: Codable {
    let runId: String
    let prompt: String
    let attachments: [AttachmentDescriptor]?
    let clientMessageId: String?
}

struct AgentStopMessagePayload: Codable {
    let runId: String
}

struct AgentCreateSessionPayload: Codable {
    let runId: String
    let projectId: String?
    let title: String
}

struct AgentRenameSessionPayload: Codable {
    let runId: String
    let title: String
}

struct AgentUpdateDraftPromptPayload: Codable {
    let runId: String
    let draftPrompt: String
}

struct AgentArchiveSessionPayload: Codable {
    let runId: String
}

struct ChatLoadHistoryPayload: Codable {
    let chatKind: String
    let chatId: String
    let before: String?
    let limit: Int
}

struct ArtifactRequestUploadPayload: Codable {
    let artifactId: String
}

struct DecisionUpdateStatusPayload: Codable {
    let decisionId: String
    let status: String
}

struct DecisionHandlePayload: Codable {
    let decisionId: String
    let runId: String
}

struct ProjectUpdatePayload: Codable {
    let project: Project
}

struct SnapshotPayload: Codable {
    let generatedAt: String
    let modelLabels: AgentModelLabels?
    let projects: [Project]
    let goals: [ProjectGoal]
    let decisions: [Decision]
    let morningBriefings: [MorningBriefing]?
    let workAssistantMessages: [WorkAssistantMessage]
    let attachments: [AttachmentDescriptor]?
    let runs: [RunDetail]
    let chatPages: [CompanionChatPage]?
}

struct ArtifactEventPayload: Codable {
    let artifact: AgentArtifact
    let attachment: AttachmentDescriptor?
}

struct AgentRunArchivedPayload: Codable {
    let id: String
    let archivedAt: String
}

struct AgentTurnSettledPayload: Codable {
    let runId: String
    let turnId: String
    let title: String
    let outcome: String
    let summary: String
    let settledAt: String
}

struct CommandResult: Codable {
    let commandId: String
    let type: CompanionCommandType?
    let status: String
    let result: JSONValue?
    let error: String?
}

struct ArtifactUploadResult: Codable {
    let artifactId: String
    let attachment: AttachmentDescriptor
}
